version: "3.9"

services:

  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: config.settings
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000"

  worker:
    build:
      context: .
      target: worker
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: config.settings

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
