version: "3.9"

services:

  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: python -m pytest

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: order_pagination
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
