version: "3.9"

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      redis:
        condition: service_healthy
    command: python src/server.py

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  redis_data:
